project:
  type: website
  resources:
    - images/**
    - projects/*.pdf

website:
  title: "Yiwei Lu"
  search:
    location: navbar
    type: overlay

  navbar:
    logo: images/logo1.png
    left:
      - href: index.qmd
        text: '<span class="nav-text">Home</span>'
      - href: news.qmd
        text: '<span class="nav-text">News</span>'
      - text: '<span class="nav-text">Projects</span>'
        menu:
          - href: projects/project.qmd
            text: '<span class="nav-text">Projects</span>'
          - href: projects/Capstone.qmd
            text: '<span class="nav-text">Capstone Project</span>'
      - text: '<span class="nav-text">Startup</span>'
        menu:
          - text: '<span style="font-size: 0.7rem; font-weight: 300; color: gray;">BETA LAUNCH</span>'
          - href: https://forecastai-poc.netlify.app/
            text: '<strong>Klug Forecast AI</strong>'
            target: _blank
          - text: '<span style="font-size: 0.7rem; font-weight: 300; color: gray;">CONCEPT STAGE</span>'
          - href: https://platemateofficial.netlify.app/
            text: '<strong>Platemate</strong>'
            target: _blank
          - href: https://skillforgeofficial.netlify.app/
            text: '<strong>Skill Forge</strong>'
            target: _blank
          - text: '<hr style="border: none; border-top: 1px solid #ccc; margin: 0.8em 0;">'
          - text: '<span style="font-size: 0.7rem; font-weight: 300; color: gray;">ABOUT</span>'
          - href: startup/journey.qmd
            text: '<strong>Startup Journey</strong>'
            target: _self
      - href: about.qmd
        text: '<span class="nav-text">About</span>'
      - href: about.qmd
        text: '<span class="nav-text">About</span>'
        target: _blank

    right:
      - icon: bell
        aria-label: Updates
        href: "#"
        target: _self
      - icon: linkedin
        href: https://www.linkedin.com/in/yiwei-lu78
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/lywww88
        aria-label: GitHub
      - icon: database
        href: https://www.kaggle.com/yiweilu
        aria-label: Kaggle
      - text: '<span class="nav-text resume-tab"><i class="bi bi-download"></i> Resume</span>'
        menu:
          - href: resume.qmd
            text: '<span class="nav-text"><i class="bi bi-eye"></i> View Resume</span>'
            target: _self
          - href: Resume_YL_2025_D1.pdf
            text: '<span class="nav-text"><i class="bi bi-file-earmark-arrow-down"></i> Download PDF</span>'
            target: _blank
      - href: ww.html
        text: '<img class="w-logo" src="/images/W.PNG" alt="W Logo">'
        aria-label: W
        icon: none
        target: _blank



format:
  html:
    theme: cosmo
    toc: true
    allow-raw-html: true
    css: styles.css
    include-in-header:
      text: |
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
        <style>
          /* hide built-in navbar search trigger, keep API available */
          #quarto-search {
            display: none !important;
            width: 0 !important;
            height: 0 !important;
            overflow: hidden !important;
            position: absolute !important;
            left: -9999px !important;
          }
        </style>
    include-after-body:
      text: |
        <!-- ========== GLOBAL: Floating Search & Back-to-Top ========== -->
        <button id="floating-search" aria-label="Search" title="Search (⌘/Ctrl + K)">
          <span id="fs-handle" aria-label="Drag" title="Drag" role="button"></span>
          <i class="bi bi-search"></i> Search
        </button>

        <button id="back-to-top" aria-label="Back to Top" title="Back to Top">
          <i class="bi bi-arrow-up"></i>
        </button>

        <!-- ========== GLOBAL: Release Modal (bell) ========== -->
        <script type="text/x-template" id="release-template">
          <p>Site Updates — 08.28.2025</p>
          <ul>
            <li>Updated Announcement Bar.</li>
            <li>Added floating Search & Back-to-Top button.</li>
            <li>Improved mobile navigation polish.</li>
            <li>Profile section redesign with gradient text and glowing avatar.</li>
          </ul>
          <p>Keyboard: <kbd>⌘/Ctrl</kbd> + <kbd>K</kbd> to search.</p>
        </script>

        <div id="release-overlay" style="display:none;"></div>
        <div id="release-modal" role="dialog" aria-modal="true" aria-labelledby="release-title" style="display:none;">
          <button class="release-close" aria-label="Close">×</button>
          <h3 id="release-title">What’s new</h3>
          <div class="release-body"></div>
          <div class="release-actions">
            <button class="release-primary" type="button">Got it</button>
          </div>
        </div>

        <style>
          /* ===== Floating Search ===== */
          #floating-search{
            position: fixed;
            right: 22px;
            bottom: 22px;
            padding: 0.6em 1.2em;
            border: none;
            border-radius: 30px;
            background: #0d6efd;
            color: #fff;
            font-weight: 600;
            font-size: 0.95rem;
            display: flex;
            align-items: center;
            gap: 0.55em;
            cursor: pointer;                 /* 点击为主 */
            box-shadow: 0 10px 24px rgba(13,110,253,.35);
            z-index: 1100;
            transition: transform .18s ease, box-shadow .18s ease, background .18s ease;
            touch-action: manipulation;      /* 移动端优先点击 */
          }
          #floating-search:hover{ transform: translateY(-2px); box-shadow: 0 14px 30px rgba(13,110,253,.45); }
          #floating-search i{ font-size: 1.1rem; }
          @media (max-width: 480px){ #floating-search{ right: 16px; bottom: 16px; } }

          #fs-handle{
            width: 14px;
            height: 18px;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            margin-right: 2px;
            cursor: grab;
            touch-action: none;              
            user-select: none;
            -webkit-user-select: none;
            opacity: .85;
          }
          #fs-handle::before{
            content: "";
            display: block;
            width: 10px; height: 14px;
            background-image:
              radial-gradient(currentColor 1px, transparent 1px),
              radial-gradient(currentColor 1px, transparent 1px),
              radial-gradient(currentColor 1px, transparent 1px);
            background-size: 4px 4px;
            background-position: 0 0, 3px 1.8px, 6px 0;
            opacity: .9;
          }
          #fs-handle:active{ cursor: grabbing; }

          /* ===== Back-to-top ===== */
          #back-to-top {
            position: fixed;
            right: 22px;
            bottom: 90px;
            width: 54px;
            height: 54px;
            border: none;
            border-radius: 50%;
            background: #0d6efd;
            color: #fff;
            display: flex;
            align-items: center;
            justify-content: center;
            box-shadow: 0 10px 24px rgba(13,110,253,.35);
            cursor: pointer;
            z-index: 1100;
            transition: transform .18s ease, box-shadow .18s ease, background .18s ease, opacity .18s ease, visibility .18s ease;
            opacity: 0; visibility: hidden;
          }
          #back-to-top:hover{ transform: translateY(-2px); box-shadow: 0 14px 30px rgba(13,110,253,.45); }
          #back-to-top:active{ transform: translateY(0) scale(.96); }
          #back-to-top i{ font-size: 1.25rem; line-height: 1; }
          @media (max-width: 480px){ #back-to-top{ right: 16px; bottom: 80px; } }

          /* ===== Modal ===== */
          #release-overlay{
            position: fixed; inset: 0; 
            background: rgba(0,0,0,.35);
            z-index: 1200;
          }
          #release-modal{
            position: fixed; 
            left: 50%; top: 50%; transform: translate(-50%, -50%);
            width: min(560px, 92vw);
            background: #fff; color:#222;
            border-radius: 12px;
            box-shadow: 0 20px 60px rgba(0,0,0,.25);
            padding: 1.2rem 1.2rem 1rem;
            z-index: 1210;
            font-family: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
          }
          #release-modal h3{ margin: 0 0 .6rem; font-size: 1.25rem; }
          #release-modal .release-body{ line-height: 1.6; color:#444; font-size: .98rem; }
          #release-modal .release-actions{ display:flex; justify-content:flex-end; gap:.6rem; margin-top: 1rem; }
          #release-modal .release-primary{
            background:#0d6efd; color:#fff; border:none; border-radius:8px;
            padding:.55rem 1rem; font-weight:600; cursor:pointer;
            box-shadow: 0 6px 16px rgba(13,110,253,.35);
          }
          #release-modal .release-primary:hover{ filter: brightness(1.05); }
          #release-modal .release-close{
            position:absolute; right:10px; top:8px;
            width:34px; height:34px; border:none; border-radius:50%;
            background: transparent; font-size: 1.2rem; cursor:pointer;
          }
          #release-modal .release-close:hover{ background:#f3f5f7; }
        </style>

        <script>
          // ===== Quarto Search Open =====
          function openSearch() {
            if (window.quartoOpenSearch) window.quartoOpenSearch();
          }
          (function () {
            const fsButton = document.getElementById('floating-search');
            if (!fsButton) return;
            fsButton.addEventListener('click', (e) => {
              if (fsButton.dataset.dragging === '1') return; 
              openSearch();
            });

            document.addEventListener('keydown', (e) => {
              const k = e.key.toLowerCase();
              if ((e.metaKey || e.ctrlKey) && k === 'k') {
                openSearch();
                e.preventDefault();
              }
            });

            const handle = document.getElementById('fs-handle');
            try {
              const saved = JSON.parse(localStorage.getItem('fs-pos') || '{}');
              if (saved.left != null && saved.top != null) {
                fsButton.style.left = saved.left + 'px';
                fsButton.style.top  = saved.top  + 'px';
                fsButton.style.right = 'auto';
                fsButton.style.bottom = 'auto';
              }
            } catch (e) {}

            let dragging = false, ox = 0, oy = 0;
            const onDown = (e) => {
              if (!(e.target === handle || (handle && handle.contains(e.target)))) return;
              dragging = true; fsButton.dataset.dragging = '1';
              const rect = fsButton.getBoundingClientRect();
              const pt = (e.touches ? e.touches[0] : e);
              ox = pt.clientX - rect.left; oy = pt.clientY - rect.top;
              e.preventDefault(); e.stopPropagation();
            };
            const onMove = (e) => {
              if (!dragging) return;
              const pt = (e.touches ? e.touches[0] : e);
              const x = pt.clientX - ox, y = pt.clientY - oy;
              fsButton.style.left = Math.max(8, Math.min(window.innerWidth  - fsButton.offsetWidth  - 8, x)) + 'px';
              fsButton.style.top  = Math.max(8, Math.min(window.innerHeight - fsButton.offsetHeight - 8, y)) + 'px';
              fsButton.style.right = 'auto'; fsButton.style.bottom = 'auto';
              e.preventDefault();
            };
            const onUp = () => {
              if (!dragging) return;
              dragging = false;
              try {
                const left = parseInt(fsButton.style.left || 0, 10);
                const top  = parseInt(fsButton.style.top  || 0, 10);
                localStorage.setItem('fs-pos', JSON.stringify({ left, top }));
              } catch (e) {}
              setTimeout(() => { fsButton.dataset.dragging = ''; }, 50);
            };

            if (handle){
              handle.addEventListener('mousedown', onDown);
              handle.addEventListener('touchstart', onDown, { passive: false });
            }
            document.addEventListener('mousemove', onMove);
            document.addEventListener('mouseup', onUp);
            document.addEventListener('touchmove', onMove, { passive: false });
            document.addEventListener('touchend', onUp);
          })();

          // ===== Back to top =====
          (function () {
            const backToTop = document.getElementById("back-to-top");
            if (!backToTop) return;
            window.addEventListener("scroll", () => {
              if (window.scrollY > 200) {
                backToTop.style.opacity = "1";
                backToTop.style.visibility = "visible";
              } else {
                backToTop.style.opacity = "0";
                backToTop.style.visibility = "hidden";
              }
            });
            backToTop.addEventListener("click", () => {
              window.scrollTo({ top: 0, behavior: "smooth" });
            });
          })();

          // ===== Bell (Updates) Modal with delegation =====
          (function(){
            const overlay = document.getElementById('release-overlay');
            const modal   = document.getElementById('release-modal');
            if (!overlay || !modal) return;

            const bodyBox = modal.querySelector('.release-body');
            const closeBtn= modal.querySelector('.release-close');
            const okBtn   = modal.querySelector('.release-primary');
            const tpl     = document.getElementById('release-template');

            if (tpl && bodyBox && !bodyBox.dataset.inited) {
              bodyBox.textContent = '';
              bodyBox.innerHTML = tpl.textContent.trim();
              bodyBox.dataset.inited = '1';
            }

            function openModal(e){
              if (e) e.preventDefault();
              overlay.style.display = 'block';
              modal.style.display   = 'block';
              document.body.style.overflow = 'hidden';
              if (closeBtn) closeBtn.focus();
              document.addEventListener('keydown', onEsc);
            }
            function closeModal(){
              overlay.style.display = 'none';
              modal.style.display   = 'none';
              document.body.style.overflow = '';
              document.removeEventListener('keydown', onEsc);
            }
            function onEsc(e){ if (e.key === 'Escape') closeModal(); }

            // 事件委托：命中右上角铃铛（多选择器兜底）
            const BELL_SELECTORS = [
              'a[aria-label="Updates"]',
              '.open-release-log',
              '.js-open-release',
              'a:has(.bi-bell)'
            ];
            document.addEventListener('click', (e) => {
              const a = e.target.closest('a');
              if (!a) return;
              const hit = BELL_SELECTORS.some(sel => {
                try { return a.matches(sel); } catch { return false; }
              }) || (a.querySelector && a.querySelector('.bi-bell'));
              if (hit) openModal(e);
            }, { capture: true });

            overlay.addEventListener('click', closeModal);
            if (closeBtn) closeBtn.addEventListener('click', closeModal);
            if (okBtn)    okBtn.addEventListener('click', closeModal);
          })();
        </script>
