project:
  type: website

website:
  title: "Portfolio of Yiwei Lu"
  navbar:
    logo: images/logo.png 
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - text: Projects
        menu:
          - href: projects/index.qmd
            text: Projects
          - href: projects/Startup.qmd
            text: Startup
    right:
    - icon: github
      href: https://github.com/lywww88
      aria-label: GitHub
    - href: resume.pdf
      text: Resume
      aria-label: Download Resume
      download: true

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
