project:
  type: website
  resources:
    - images/**         
    - projects/*.pdf

website:
  title: "Yiwei Lu"
  navbar:
    logo: images/logo1.png
    left:
      - href: index.qmd
        text: '<span class="nav-text">Home</span>'

      - text: '<span class="nav-text">Projects</span>'
        menu:
          - href: projects/index.qmd
            text: '<span class="nav-text">Projects</span>'
          - href: projects/Capstone.qmd
            text: '<span class="nav-text">Capstone Project</span>'

      - text: '<span class="nav-text">Startup</span>'
        menu:
          - text: '<span style="font-size: 0.7rem; font-weight: 300; color: gray;">BETA LAUNCH</span>'
          - href: https://forecastai-poc.netlify.app/
            text: '<strong>Klug Forecast AI</strong>'
            target: _blank

          - text: '<span style="font-size: 0.7rem; font-weight: 300; color: gray;">CONCEPT STAGE</span>'
          - href: https://platemateofficial.netlify.app/
            text: '<strong>Platemate</strong>'
            target: _blank
          - href: https://skillforgeofficial.netlify.app/
            text: '<strong>Skill Forge</strong>'
            target: _blank

          - text: '<hr style="border: none; border-top: 1px solid #ccc; margin: 0.8em 0;">'
          - text: '<span style="font-size: 0.7rem; font-weight: 300; color: gray;">ABOUT</span>'
          - href: startup/journey.qmd
            text: '<strong>Startup Journey</strong>'
            target: _self

      - href: about.qmd
        text: '<span class="nav-text">About</span>'

    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/yiwei-lu78
        aria-label: LinkedIn

      - icon: github
        href: https://github.com/lywww88
        aria-label: GitHub

      - icon: database
        href: https://www.kaggle.com/yiweilu  
        aria-label: Kaggle

      - text: '<span class="nav-text resume-tab"><i class="bi bi-download"></i> Resume</span>'
        menu:
          - href: resume.qmd
            text: '<span class="nav-text"><i class="bi bi-eye"></i> View Resume</span>'
            target: _self
          - href: Resume_YL_2025_D1.pdf
            text: '<span class="nav-text"><i class="bi bi-file-earmark-arrow-down"></i> Download PDF</span>'
            target: _blank

      - href: ww.qmd
        text: '<img class="w-logo" src="/images/W.PNG" alt="W Logo">'
        aria-label: W
        icon: none
        target: _blank

format:
  html:
    theme: cosmo
    toc: true
    allow-raw-html: true
    css: styles.css
    include-in-header:
      text: |
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
