project:
  type: website

website:
  title: "Portfolio - Yiwei Lu"
  navbar:
    logo: images/logo1.png
    left:
      - href: index.qmd
        text: '<span class="nav-text">Home</span>'
      - href: projects/index.qmd            # ← 给顶层 Projects 加上 href
        text: '<span class="nav-text">Projects</span>'
        menu:
          - href: projects/index.qmd
            text: '<span class="nav-text">Projects</span>'
          - href: projects/capstone.qmd
            text: '<span class="nav-text">Capstone</span>'
      - href: about.qmd
        text: '<span class="nav-text">About</span>'
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/yiwei-lu78
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/lywww88
        aria-label: GitHub
      - icon: database
        href: https://www.kaggle.com/yiweilu
        aria-label: Kaggle
      - href: resume.pdf
        text: '<span class="nav-text"><i class="bi bi-download"></i> Resume</span>'
        aria-label: Resume
        target: _blank
      - href: ww.html
        text: 🦖
        aria-label: Life
        icon: none
        target: _self

format:
  html:
    theme: cosmo
    toc: true
    allow-raw-html: true
    css: styles.css
    include-in-header:
      text: |
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
