project:
  type: website

website:
  title: "Portfolio - Yiwei Lu"
  navbar:
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Projects
        menu:
          - href: projects/index.qmd
            text: School Projects
          - href: projects/index.qmd
            text: Capstone Project
      - href: projects/Startup.qmd
        text: Startup
    right:
      - icon: github
        href: https://github.com/lywww88
        aria-label: GitHub
      - href: resume.pdf
        text: Resume
        icon: download
        target: _blank

format:
  html:
    theme:
      - cosmo
    toc: true
    allow-raw-html: true
    css:
      - styles.css
