project:
  type: website

website:
  title: "Portfolio - Yiwei Lu"
  navbar:
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:
          - href: projects/index.qmd
            text: School Projects
          - href: projects/index.qmd
            text: Capstone Project
      - text: Startup
        menu:
          - href: https://forecastai-poc.netlify.app/
            text: FoodAI
            target: _blank
          - href: https://www.instagram.com/platemateofficial/profilecard
            text: Platemate
            target: _blank
      - href: about.qmd
        text: About
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/yiwei-lu78
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/lywww88
        aria-label: GitHub
      - href: resume.pdf
        text: Resume
        icon: download
        target: _blank

format:
  html:
    theme:
      - cosmo
    toc: true
    allow-raw-html: true
    css:
      - styles.css
