project:
  type: website
  resources:
    - images/**
    - projects/*.pdf

website:
  title: "Yiwei Lu"
  search:
    location: navbar
    type: overlay

  navbar:
    logo: images/logo1.png
    left:
      - href: index.qmd
        text: '<span class="nav-text">Home</span>'
      - href: news.qmd
        text: '<span class="nav-text">News</span>'
      - text: '<span class="nav-text">Projects</span>'
        menu:
          - href: projects/index.qmd
            text: '<span class="nav-text">Projects</span>'
          - href: projects/Capstone.qmd
            text: '<span class="nav-text">Capstone Project</span>'
      - text: '<span class="nav-text">Startup</span>'
        menu:
          - text: '<span style="font-size: 0.7rem; font-weight: 300; color: gray;">BETA LAUNCH</span>'
          - href: https://forecastai-poc.netlify.app/
            text: '<strong>Klug Forecast AI</strong>'
            target: _blank
          - text: '<span style="font-size: 0.7rem; font-weight: 300; color: gray;">CONCEPT STAGE</span>'
          - href: https://platemateofficial.netlify.app/
            text: '<strong>Platemate</strong>'
            target: _blank
          - href: https://skillforgeofficial.netlify.app/
            text: '<strong>Skill Forge</strong>'
            target: _blank
          - text: '<hr style="border: none; border-top: 1px solid #ccc; margin: 0.8em 0;">'
          - text: '<span style="font-size: 0.7rem; font-weight: 300; color: gray;">ABOUT</span>'
          - href: startup/journey.qmd
            text: '<strong>Startup Journey</strong>'
            target: _self
      - href: about.qmd
        text: '<span class="nav-text">About</span>'

    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/yiwei-lu78
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/lywww88
        aria-label: GitHub
      - icon: database
        href: https://www.kaggle.com/yiweilu
        aria-label: Kaggle
      - icon: bell
        aria-label: Updates
        href: "#"
        text: ""
        target: _self
        attributes:
          class: "open-release-log"
      - text: '<span class="nav-text resume-tab"><i class="bi bi-download"></i> Resume</span>'
        menu:
          - href: resume.qmd
            text: '<span class="nav-text"><i class="bi bi-eye"></i> View Resume</span>'
            target: _self
          - href: Resume_YL_2025_D1.pdf
            text: '<span class="nav-text"><i class="bi bi-file-earmark-arrow-down"></i> Download PDF</span>'
            target: _blank
      - href: ww.html
        text: '<img class="w-logo" src="/images/W.PNG" alt="W Logo">'
        aria-label: W
        icon: none
        target: _blank


format:
  html:
    theme: cosmo
    toc: true
    allow-raw-html: true
    css: styles.css
    include-in-header:
      text: |
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
        <style>
          /* hide built-in navbar search trigger, keep API available */
          #quarto-search {
            display: none !important;
            width: 0 !important;
            height: 0 !important;
            overflow: hidden !important;
            position: absolute !important;
            left: -9999px !important;
          }
        </style>
    include-after-body:
      text: |
        <!-- Floating, draggable Search (handle-only dragging) -->
        <button id="floating-search" aria-label="Search" title="Search (⌘/Ctrl + K)">
          <span id="fs-handle" aria-label="Drag" title="Drag" role="button"></span>
          <i class="bi bi-search"></i> Search
        </button>

        <!-- Floating Back-to-Top -->
        <button id="back-to-top" aria-label="Back to Top" title="Back to Top">
          <i class="bi bi-arrow-up"></i>
        </button>

        <style>
          /* Search pill：按钮默认点击；拖动交给把手 */
          #floating-search{
            position: fixed;
            right: 22px;
            bottom: 22px;
            padding: 0.6em 1.2em;
            border: none;
            border-radius: 30px;
            background: #0d6efd;
            color: #fff;
            font-weight: 600;
            font-size: 0.95rem;
            display: flex;
            align-items: center;
            gap: 0.55em;
            cursor: pointer;                 /* 点击为主 */
            box-shadow: 0 10px 24px rgba(13,110,253,.35);
            z-index: 1100;
            transition: transform .18s ease, box-shadow .18s ease, background .18s ease;
            touch-action: manipulation;      /* 移动端优先点击 */
          }
          #floating-search:hover{ transform: translateY(-2px); box-shadow: 0 14px 30px rgba(13,110,253,.45); }
          #floating-search i{ font-size: 1.1rem; }
          @media (max-width: 480px){ #floating-search{ right: 16px; bottom: 16px; } }

          /* 把手：只有它能拖动 */
          #fs-handle{
            width: 14px;
            height: 18px;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            margin-right: 2px;
            cursor: grab;
            touch-action: none;              /* 允许拖动手势 */
            user-select: none;
            -webkit-user-select: none;
            opacity: .85;
          }
          /* 把手纹理（竖向 3 列点点） */
          #fs-handle::before{
            content: "";
            display: block;
            width: 10px; height: 14px;
            background-image:
              radial-gradient(currentColor 1px, transparent 1px),
              radial-gradient(currentColor 1px, transparent 1px),
              radial-gradient(currentColor 1px, transparent 1px);
            background-size: 4px 4px;
            background-position: 0 0, 3px 1.8px, 6px 0;
            opacity: .9;
          }
          #fs-handle:active{ cursor: grabbing; }

          /* Back-to-top */
          #back-to-top {
            position: fixed;
            right: 22px;
            bottom: 90px; /* above search */
            width: 54px;
            height: 54px;
            border: none;
            border-radius: 50%;
            background: #0d6efd;
            color: #fff;
            display: flex;
            align-items: center;
            justify-content: center;
            box-shadow: 0 10px 24px rgba(13,110,253,.35);
            cursor: pointer;
            z-index: 1100;
            transition: transform .18s ease, box-shadow .18s ease, background .18s ease, opacity .18s ease, visibility .18s ease;
            opacity: 0;
            visibility: hidden;
          }
          #back-to-top:hover{ transform: translateY(-2px); box-shadow: 0 14px 30px rgba(13,110,253,.45); }
          #back-to-top:active{ transform: translateY(0) scale(.96); }
          #back-to-top i{ font-size: 1.25rem; line-height: 1; }
          @media (max-width: 480px){ #back-to-top{ right: 16px; bottom: 80px; } }
        </style>

        <script>
          // Open Quarto search
          function openSearch() {
            if (window.quartoOpenSearch) window.quartoOpenSearch();
          }

          const fsButton = document.getElementById('floating-search');
          fsButton.addEventListener('click', (e) => {
            // 若刚结束拖动，阻止本次点击
            if (fsButton.dataset.dragging === '1') return;
            openSearch();
          });

          // Keyboard shortcut: Cmd/Ctrl + K
          document.addEventListener('keydown', (e) => {
            const k = e.key.toLowerCase();
            if ((e.metaKey || e.ctrlKey) && k === 'k') {
              openSearch();
              e.preventDefault();
            }
          });

          // Handle-only draggable with saved position
          (function () {
            const btn = document.getElementById('floating-search');
            const handle = document.getElementById('fs-handle');
            if (!btn || !handle) return;

            // 恢复位置
            try {
              const saved = JSON.parse(localStorage.getItem('fs-pos') || '{}');
              if (saved.left != null && saved.top != null) {
                btn.style.left = saved.left + 'px';
                btn.style.top  = saved.top  + 'px';
                btn.style.right = 'auto';
                btn.style.bottom = 'auto';
              }
            } catch (e) {}

            let dragging = false, ox = 0, oy = 0;

            const onDown = (e) => {
              // 仅把手触发拖动
              if (!(e.target === handle || handle.contains(e.target))) return;

              dragging = true;
              btn.dataset.dragging = '1';
              const rect = btn.getBoundingClientRect();
              const pt = (e.touches ? e.touches[0] : e);
              ox = pt.clientX - rect.left;
              oy = pt.clientY - rect.top;
              e.preventDefault();
              e.stopPropagation();
            };

            const onMove = (e) => {
              if (!dragging) return;
              const pt = (e.touches ? e.touches[0] : e);
              const x = pt.clientX - ox;
              const y = pt.clientY - oy;
              btn.style.left = Math.max(8, Math.min(window.innerWidth  - btn.offsetWidth  - 8, x)) + 'px';
              btn.style.top  = Math.max(8, Math.min(window.innerHeight - btn.offsetHeight - 8, y)) + 'px';
              btn.style.right = 'auto';
              btn.style.bottom = 'auto';
              e.preventDefault();
            };

            const onUp = () => {
              if (!dragging) return;
              dragging = false;
              try {
                const left = parseInt(btn.style.left || 0, 10);
                const top  = parseInt(btn.style.top  || 0, 10);
                localStorage.setItem('fs-pos', JSON.stringify({ left, top }));
              } catch (e) {}
              // 结束后短暂阻止 click（避免“拖完就点开搜索”）
              setTimeout(() => { btn.dataset.dragging = ''; }, 50);
            };

            // 只在把手上绑定按下；移动/抬起监听全局
            handle.addEventListener('mousedown', onDown);
            handle.addEventListener('touchstart', onDown, { passive: false });
            document.addEventListener('mousemove', onMove);
            document.addEventListener('mouseup', onUp);
            document.addEventListener('touchmove', onMove, { passive: false });
            document.addEventListener('touchend', onUp);
          })();

          // Back to top
          const backToTop = document.getElementById("back-to-top");
          window.addEventListener("scroll", () => {
            if (window.scrollY > 200) {
              backToTop.style.opacity = "1";
              backToTop.style.visibility = "visible";
            } else {
              backToTop.style.opacity = "0";
              backToTop.style.visibility = "hidden";
            }
          });
          backToTop.addEventListener("click", () => {
            window.scrollTo({ top: 0, behavior: "smooth" });
          });
        </script>
